package machine_problem1;

public class Menu extends javax.swing.JFrame {
    int counter = 0;

    public Menu() {
        initComponents();
        setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
        setSize (930, 530);
        setLocationRelativeTo(null);
        setLayout (null);
        setResizable(false);
        setTitle("Machine Problem #1 - Barcos, Jim Aerol S.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btn_Tree = new javax.swing.JButton();
        Btn_Array = new javax.swing.JButton();
        Btn_LinkedList = new javax.swing.JButton();
        Btn_Stack = new javax.swing.JButton();
        Btn_Queue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Image_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 500));
        setPreferredSize(new java.awt.Dimension(930, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/med-350x300.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 330, 280));

        Btn_Tree.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Tree.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Btn_Tree.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Tree.setText("TREE");
        Btn_Tree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Tree.setFocusable(false);
        Btn_Tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TreeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 210, 70));

        Btn_Array.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Array.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Btn_Array.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Array.setText("ARRAY");
        Btn_Array.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Array.setFocusable(false);
        Btn_Array.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ArrayActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Array, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 210, 70));

        Btn_LinkedList.setBackground(new java.awt.Color(255, 102, 51));
        Btn_LinkedList.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Btn_LinkedList.setForeground(new java.awt.Color(255, 255, 255));
        Btn_LinkedList.setText("LINKED LIST");
        Btn_LinkedList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_LinkedList.setFocusable(false);
        Btn_LinkedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LinkedListActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_LinkedList, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 70));

        Btn_Stack.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Stack.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Btn_Stack.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Stack.setText("STACK");
        Btn_Stack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Stack.setFocusable(false);
        Btn_Stack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_StackMouseClicked(evt);
            }
        });
        Btn_Stack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StackActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Stack, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 210, 70));

        Btn_Queue.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Queue.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Btn_Queue.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Queue.setText("QUEUE");
        Btn_Queue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Queue.setFocusable(false);
        Btn_Queue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_QueueActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Queue, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 210, 70));

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("- Menu Page -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("has come. Let's learn it!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 460, -1));

        jLabel4.setBackground(new java.awt.Color(255, 204, 102));
        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Data Structures Toolkit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hello Medieval Warrior, an");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, -1));

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("astonishing discovery in the");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 460, -1));

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("field of math & algorithms");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 460, -1));

        Image_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-930x500.jpg"))); // NOI18N
        Image_BG.setPreferredSize(new java.awt.Dimension(930, 530));
        getContentPane().add(Image_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));
        Image_BG.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_TreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TreeActionPerformed
        Trees logFrame = new Trees();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_TreeActionPerformed

    private void Btn_LinkedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LinkedListActionPerformed
        LinkedList logFrame = new LinkedList();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_LinkedListActionPerformed

    private void Btn_StackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StackActionPerformed
        Stacks logFrame = new Stacks();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_StackActionPerformed

    private void Btn_QueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_QueueActionPerformed
        Queues logFrame = new Queues();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_QueueActionPerformed

    private void Btn_ArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ArrayActionPerformed
        Array logFrame = new Array();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_ArrayActionPerformed

    private void Btn_StackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_StackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_StackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Array;
    private javax.swing.JButton Btn_LinkedList;
    private javax.swing.JButton Btn_Queue;
    private javax.swing.JButton Btn_Stack;
    private javax.swing.JButton Btn_Tree;
    private javax.swing.JLabel Image_BG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
