package machine_problem1;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

public class Queues extends javax.swing.JFrame {
    int counter = 0, num_counter = 0;;
    boolean exist = false;
    QueuesAlgo DerivedQueue;
    

    public Queues() {
        initComponents();
        setDefaultCloseOperation(Queues.EXIT_ON_CLOSE);
        setSize (930, 530);
        setLocationRelativeTo(null);
        setLayout (null);
        setResizable(false);
        setTitle("Machine Problem #1 - Barcos, Jim Aerol S.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Display = new javax.swing.JButton();
        Btn_Empty = new javax.swing.JButton();
        Btn_Enqueue = new javax.swing.JButton();
        Btn_Dequeue = new javax.swing.JButton();
        Btn_Front = new javax.swing.JButton();
        Btn_Back = new javax.swing.JLabel();
        Btn_Rear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Txt_Area = new javax.swing.JTextArea();
        Image_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Display.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Display.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Display.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Display.setText("(6) Display the Queue");
        Btn_Display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Display.setFocusable(false);
        Btn_Display.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DisplayMouseClicked(evt);
            }
        });
        Btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 50));

        Btn_Empty.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Empty.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Btn_Empty.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Empty.setText("(1) Create an Empty Queue");
        Btn_Empty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Empty.setFocusable(false);
        Btn_Empty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Empty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_EmptyMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Empty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 50));

        Btn_Enqueue.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Enqueue.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Btn_Enqueue.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Enqueue.setText("(2) ENQUEUE elements");
        Btn_Enqueue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Enqueue.setFocusable(false);
        Btn_Enqueue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Enqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_EnqueueMouseClicked(evt);
            }
        });
        Btn_Enqueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnqueueActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Enqueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 50));

        Btn_Dequeue.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Dequeue.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Btn_Dequeue.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Dequeue.setText("(3) DEQUEUE elements");
        Btn_Dequeue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Dequeue.setFocusable(false);
        Btn_Dequeue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Dequeue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DequeueMouseClicked(evt);
            }
        });
        Btn_Dequeue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DequeueActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Dequeue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, 210, 50));

        Btn_Front.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Front.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Front.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Front.setText("(4) Check FRONT");
        Btn_Front.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Front.setFocusable(false);
        Btn_Front.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Front.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_FrontMouseClicked(evt);
            }
        });
        Btn_Front.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FrontActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Front, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 50));

        Btn_Back.setBackground(new java.awt.Color(255, 204, 102));
        Btn_Back.setFont(new java.awt.Font("Segoe UI Symbol", 1, 60)); // NOI18N
        Btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back.setText("←");
        Btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_BackMouseExited(evt);
            }
        });
        getContentPane().add(Btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        Btn_Rear.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Rear.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Rear.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Rear.setText("(5) Check REAR");
        Btn_Rear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Rear.setFocusable(false);
        Btn_Rear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Rear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_RearMouseClicked(evt);
            }
        });
        Btn_Rear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RearActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Rear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 210, 50));

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Queues");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        Txt_Area.setEditable(false);
        Txt_Area.setBackground(new java.awt.Color(255, 239, 135));
        Txt_Area.setColumns(20);
        Txt_Area.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_Area.setLineWrap(true);
        Txt_Area.setRows(1);
        Txt_Area.setToolTipText("");
        Txt_Area.setWrapStyleWord(true);
        Txt_Area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 0, 0), 5, true));
        Txt_Area.setDragEnabled(true);
        Txt_Area.setFocusable(false);
        jScrollPane7.setViewportView(Txt_Area);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 640, 390));

        Image_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-930x500.jpg"))); // NOI18N
        Image_BG.setPreferredSize(new java.awt.Dimension(930, 530));
        getContentPane().add(Image_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));
        Image_BG.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DisplayActionPerformed

    private void Btn_EnqueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnqueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EnqueueActionPerformed

    private void Btn_DequeueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DequeueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DequeueActionPerformed

    private void Btn_FrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FrontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_FrontActionPerformed

    private void Btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseClicked
        Menu logFrame = new Menu();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_BackMouseClicked

    private void Btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseEntered
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 51, 51));
    }//GEN-LAST:event_Btn_BackMouseEntered

    private void Btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseExited
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Btn_BackMouseExited

    private void Btn_RearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_RearActionPerformed

    private void Btn_EmptyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EmptyMouseClicked
        if (exist){
            if (JOptionPane.showConfirmDialog(null, "Create A new empty Queue (This will overwrite the previous Queue)", "Create Queue", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
               exist = false;
            }
        }
        
        if (exist == false) {
            try {
                String userInput = JOptionPane.showInputDialog(null, "Please enter how many storage for Queue:" , "Create element - Queue", JOptionPane.INFORMATION_MESSAGE);
                int int_Input = Integer.parseInt(userInput);
                DerivedQueue = new QueuesAlgo(int_Input);
                Txt_Area.setText(Txt_Area.getText() + "• Successfully Completed Creating An empty Queue with " + int_Input + " size\n\n");
                JOptionPane.showMessageDialog(null, "Successfully Completed Creating An empty Queue with " + int_Input + " size", "Create Queue", JOptionPane.INFORMATION_MESSAGE);
                exist = true;
                num_counter = 1;
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_Btn_EmptyMouseClicked

    private void Btn_EnqueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EnqueueMouseClicked
        try{
            if (exist){
            String userInput = JOptionPane.showInputDialog(null, "Please enter the element #" + (num_counter), "Push element - Queue", JOptionPane.INFORMATION_MESSAGE);
            try {
                int int_Input = Integer.parseInt(userInput);
                
                if (DerivedQueue.enqueueData(int_Input) == 2){
                    num_counter++;
                    Txt_Area.setText(Txt_Area.getText() + "• Value " + int_Input + " inserted in the Queue\n\n");
                }else {
                    Txt_Area.setText(Txt_Area.getText() + "• QUEUEOVERFLOW\n\n");
                }
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Push element - Queue", JOptionPane.INFORMATION_MESSAGE);
              }
            
            } else {
                JOptionPane.showMessageDialog(null, "Please Create first an empty Queue", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EnqueueMouseClicked

    private void Btn_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DisplayMouseClicked
        try {
        if (exist){
            try {
                Txt_Area.setText(Txt_Area.getText() + "• Values of the Queue: [  ");
                Txt_Area.setText(Txt_Area.getText()  + String.valueOf(DerivedQueue.displayData()) + " ");
                Txt_Area.setText(Txt_Area.getText() + "]\n\n");
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Queue", JOptionPane.INFORMATION_MESSAGE);
              }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please Create first an empty Queue", "Display element - Queue", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Queue", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DisplayMouseClicked

    private void Btn_DequeueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DequeueMouseClicked
        if (exist){
            try {
                int value_pop = DerivedQueue.dequeueData();
                
                if (value_pop != -1){
                    Txt_Area.setText(Txt_Area.getText() + "• Dequeue the value of " + value_pop);
                } else {
                    Txt_Area.setText(Txt_Area.getText() + "• QUEUEUNDERFLOW");
                }
                Txt_Area.setText(Txt_Area.getText() + "\n\n");
                
              } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Dequeue element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
              }
        } else {
            JOptionPane.showMessageDialog(null, "Please Create & insert values first on the Queue", "Dequeue element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DequeueMouseClicked

    private void Btn_FrontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_FrontMouseClicked
        if (exist){
            try {
                int value_front = DerivedQueue.checkFrontData();
                
                if (value_front != -1){
                    Txt_Area.setText(Txt_Area.getText() + "• Front value of Queue is " + value_front);
                } else {
                    Txt_Area.setText(Txt_Area.getText() + "• Invalid Codition, make sure Queue has contents");
                }
                Txt_Area.setText(Txt_Area.getText() + "\n\n");
                
              } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Front element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
              }
        } else {
            JOptionPane.showMessageDialog(null, "Please Create & insert values first on the Queue", "Front element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_FrontMouseClicked

    private void Btn_RearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_RearMouseClicked
       if (exist){
            try {
                int value_rear = DerivedQueue.checkRearData();
                
                if (value_rear != -1){
                    Txt_Area.setText(Txt_Area.getText() + "• Rear value of Queue is " + value_rear);
                } else {
                    Txt_Area.setText(Txt_Area.getText() + "• Invalid Codition, make sure Queue has contents");
                }
                Txt_Area.setText(Txt_Area.getText() + "\n\n");
                
              } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Rear element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
              }
        } else {
            JOptionPane.showMessageDialog(null, "Please Create & insert values first on the Queue", "Rear element - Dequeue", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_RearMouseClicked


    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Back;
    private javax.swing.JButton Btn_Dequeue;
    private javax.swing.JButton Btn_Display;
    private javax.swing.JButton Btn_Empty;
    private javax.swing.JButton Btn_Enqueue;
    private javax.swing.JButton Btn_Front;
    private javax.swing.JButton Btn_Rear;
    private javax.swing.JLabel Image_BG;
    private javax.swing.JTextArea Txt_Area;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
