package machine_problem1;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import machine_problem1.StackAlgo; 


public class Stacks extends javax.swing.JFrame {
    int counter = 0, num_counter = 0;;
    boolean exist = false;
    StackAlgo DerivedStacks;
    
    //StackAlgo DerivedStacks = new StackAlgo(5);
    
    public Stacks() {
       
        initComponents();
        setDefaultCloseOperation(Stacks.EXIT_ON_CLOSE);
        setSize (930, 530);
        setLocationRelativeTo(null);
        setLayout (null);
        setResizable(false);
        setTitle("Machine Problem #1 - Barcos, Jim Aerol S.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Display = new javax.swing.JButton();
        Btn_Create = new javax.swing.JButton();
        Btn_Push = new javax.swing.JButton();
        Btn_Pop = new javax.swing.JButton();
        Btn_Change = new javax.swing.JButton();
        Btn_Back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Txt_Area = new javax.swing.JTextArea();
        Image_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Display.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Display.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Display.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Display.setText("(5) Display the Stack");
        Btn_Display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Display.setFocusable(false);
        Btn_Display.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DisplayMouseClicked(evt);
            }
        });
        Btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 70));

        Btn_Create.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Create.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Btn_Create.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Create.setText("(1) Create an Empty Stack");
        Btn_Create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Create.setFocusable(false);
        Btn_Create.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CreateMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 70));

        Btn_Push.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Push.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Push.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Push.setText("(2) PUSH elements");
        Btn_Push.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Push.setFocusable(false);
        Btn_Push.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Push.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_PushMouseClicked(evt);
            }
        });
        Btn_Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PushActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Push, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 70));

        Btn_Pop.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Pop.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Pop.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Pop.setText("(3) POP elements");
        Btn_Pop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Pop.setFocusable(false);
        Btn_Pop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Pop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_PopMouseClicked(evt);
            }
        });
        Btn_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PopActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 70));

        Btn_Change.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Change.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Btn_Change.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Change.setText("(4) Change specific element");
        Btn_Change.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Change.setFocusable(false);
        Btn_Change.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ChangeMouseClicked(evt);
            }
        });
        Btn_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChangeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 70));

        Btn_Back.setBackground(new java.awt.Color(255, 204, 102));
        Btn_Back.setFont(new java.awt.Font("Segoe UI Symbol", 1, 60)); // NOI18N
        Btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back.setText("←");
        Btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_BackMouseExited(evt);
            }
        });
        getContentPane().add(Btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Stacks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        Txt_Area.setEditable(false);
        Txt_Area.setBackground(new java.awt.Color(255, 239, 135));
        Txt_Area.setColumns(20);
        Txt_Area.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_Area.setLineWrap(true);
        Txt_Area.setRows(1);
        Txt_Area.setToolTipText("");
        Txt_Area.setWrapStyleWord(true);
        Txt_Area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 0, 0), 5, true));
        Txt_Area.setDragEnabled(true);
        Txt_Area.setFocusable(false);
        jScrollPane7.setViewportView(Txt_Area);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 640, 390));

        Image_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-930x500.jpg"))); // NOI18N
        Image_BG.setPreferredSize(new java.awt.Dimension(930, 530));
        getContentPane().add(Image_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));
        Image_BG.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DisplayActionPerformed
 
    }//GEN-LAST:event_Btn_DisplayActionPerformed

    private void Btn_PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PushActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_PushActionPerformed

    private void Btn_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_PopActionPerformed

    private void Btn_ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ChangeActionPerformed

    private void Btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseClicked
        Menu logFrame = new Menu();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_BackMouseClicked

    private void Btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseEntered
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 51, 51));
    }//GEN-LAST:event_Btn_BackMouseEntered

    private void Btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseExited
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Btn_BackMouseExited

    private void Btn_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CreateMouseClicked

        if (exist){
            if (JOptionPane.showConfirmDialog(null, "Create A new empty Stack (This will overwrite the previous Stack)", "Create Stack", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
               exist = false;
            }
        }
        
        if (exist == false) {
            try {
                String userInput = JOptionPane.showInputDialog(null, "Please enter how many storage for stack:" , "Create element - Stack", JOptionPane.INFORMATION_MESSAGE);
                int int_Input = Integer.parseInt(userInput);
                DerivedStacks = new StackAlgo(int_Input);
                Txt_Area.setText(Txt_Area.getText() + "• Successfully Completed Creating An empty Stack with " + int_Input + " size\n\n");
                JOptionPane.showMessageDialog(null, "Successfully Completed Creating An empty Stack with " + int_Input + " size", "Create Stack", JOptionPane.INFORMATION_MESSAGE);
                exist = true;
                num_counter = 1;
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Create element - Stack", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_Btn_CreateMouseClicked

    private void Btn_PushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_PushMouseClicked
         try{
            if (exist){
            String userInput = JOptionPane.showInputDialog(null, "Please enter the element #" + (num_counter), "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
            try {
                int int_Input = Integer.parseInt(userInput);
                
                if (DerivedStacks.pushData(int_Input) == 2){
                    num_counter++;
                    Txt_Area.setText(Txt_Area.getText() + "• Value " + int_Input + " inserted in the Stack\n\n");
                }else {
                    Txt_Area.setText(Txt_Area.getText() + "• STACKOVERFLOW\n\n");
                }
                
                
                
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
              }
            
            } else {
                JOptionPane.showMessageDialog(null, "Please Create first an empty Stack", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Push element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_PushMouseClicked

    private void Btn_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DisplayMouseClicked

        try {
        if (exist){
            try {
                Txt_Area.setText(Txt_Area.getText() + "• Values of the Stack: [  ");
                Txt_Area.setText(Txt_Area.getText()  + String.valueOf(DerivedStacks.displayStack()) + " ");
                Txt_Area.setText(Txt_Area.getText() + "]\n\n");
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Stack", JOptionPane.INFORMATION_MESSAGE);
              }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please Create first an empty Stack", "Display element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DisplayMouseClicked

    private void Btn_PopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_PopMouseClicked
        if (exist){
            try {
                int value_pop = DerivedStacks.popData();
                
                if (value_pop != -1){
                    Txt_Area.setText(Txt_Area.getText() + "• Popped the value of " + value_pop);
                } else {
                    Txt_Area.setText(Txt_Area.getText() + "• STACKUNDERFLOW");
                }
                Txt_Area.setText(Txt_Area.getText() + "\n\n");
                
              } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Pop element - Stack", JOptionPane.INFORMATION_MESSAGE);
              }
        } else {
            JOptionPane.showMessageDialog(null, "Please Create & insert values first on the Stack", "Pop element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_PopMouseClicked

    private void Btn_ChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ChangeMouseClicked
        if (exist){
            try {
                String userInput = JOptionPane.showInputDialog(null, "Please enter the index to be replaced" , "Change element - Stack", JOptionPane.INFORMATION_MESSAGE);
                int int_Input = Integer.parseInt(userInput);
                
                String userValue = JOptionPane.showInputDialog(null, "Please enter the new value of the index" , "Change element - Stack", JOptionPane.INFORMATION_MESSAGE);
                int int_Value = Integer.parseInt(userValue);
                
                int value_change = DerivedStacks.changeElementData(int_Input, int_Value);
                
                if (value_change != 2){
                    Txt_Area.setText(Txt_Area.getText() + "• Change the value of element " + int_Input + " to " + int_Value);
                } else {
                    Txt_Area.setText(Txt_Area.getText() + "• Index out of range");
                }
                Txt_Area.setText(Txt_Area.getText() + "\n\n");
                
              } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Change element - Stack", JOptionPane.INFORMATION_MESSAGE);
              }
        } else {
            JOptionPane.showMessageDialog(null, "Please Create & insert values first on the Stack", "Change element - Stack", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_ChangeMouseClicked


    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stacks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Back;
    private javax.swing.JButton Btn_Change;
    private javax.swing.JButton Btn_Create;
    private javax.swing.JButton Btn_Display;
    private javax.swing.JButton Btn_Pop;
    private javax.swing.JButton Btn_Push;
    private javax.swing.JLabel Image_BG;
    private javax.swing.JTextArea Txt_Area;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
