package machine_problem1;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

class TreeData {
    int parentNodes;
    int leafNodes;
    int levels;

    public TreeData(int parentNodes, int leafNodes, int levels) {
        this.parentNodes = parentNodes;
        this.leafNodes = leafNodes;
        this.levels = levels;
    }
}

public class Trees extends javax.swing.JFrame {
    int counter = 0, num_counter = 0;;
    boolean exist = false;
    TreesAlgo DerivedTree;

    public Trees() {
        initComponents();
        setDefaultCloseOperation(Trees.EXIT_ON_CLOSE);
        setSize (930, 530);
        setLocationRelativeTo(null);
        setLayout (null);
        setResizable(false);
        setTitle("Machine Problem #1 - Barcos, Jim Aerol S.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_DisplayTree = new javax.swing.JButton();
        Btn_Create = new javax.swing.JButton();
        Btn_Insert = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        Btn_Display = new javax.swing.JButton();
        Btn_Back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Txt_Area = new javax.swing.JTextArea();
        Image_BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_DisplayTree.setBackground(new java.awt.Color(255, 102, 51));
        Btn_DisplayTree.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Btn_DisplayTree.setForeground(new java.awt.Color(255, 255, 255));
        Btn_DisplayTree.setText("(5) Display Tree Structure");
        Btn_DisplayTree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_DisplayTree.setFocusable(false);
        Btn_DisplayTree.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_DisplayTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DisplayTreeMouseClicked(evt);
            }
        });
        Btn_DisplayTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DisplayTreeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_DisplayTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 70));

        Btn_Create.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Create.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        Btn_Create.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Create.setText("(1) Create an Empty BT");
        Btn_Create.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Create.setFocusable(false);
        Btn_Create.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CreateMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 70));

        Btn_Insert.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Insert.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Insert.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Insert.setText("(2) Insert elements");
        Btn_Insert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Insert.setFocusable(false);
        Btn_Insert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_InsertMouseClicked(evt);
            }
        });
        Btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 70));

        Btn_Delete.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Delete.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Delete.setText("(3) Delete an element");
        Btn_Delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Delete.setFocusable(false);
        Btn_Delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DeleteMouseClicked(evt);
            }
        });
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 70));

        Btn_Display.setBackground(new java.awt.Color(255, 102, 51));
        Btn_Display.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        Btn_Display.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Display.setText("(4) Display Binary Tree");
        Btn_Display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));
        Btn_Display.setFocusable(false);
        Btn_Display.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btn_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DisplayMouseClicked(evt);
            }
        });
        Btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 70));

        Btn_Back.setBackground(new java.awt.Color(255, 204, 102));
        Btn_Back.setFont(new java.awt.Font("Segoe UI Symbol", 1, 60)); // NOI18N
        Btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back.setText("←");
        Btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_BackMouseExited(evt);
            }
        });
        getContentPane().add(Btn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Binary Tree");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        Txt_Area.setEditable(false);
        Txt_Area.setBackground(new java.awt.Color(255, 239, 135));
        Txt_Area.setColumns(20);
        Txt_Area.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Txt_Area.setLineWrap(true);
        Txt_Area.setRows(1);
        Txt_Area.setToolTipText("");
        Txt_Area.setWrapStyleWord(true);
        Txt_Area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 0, 0), 5, true));
        Txt_Area.setDragEnabled(true);
        Txt_Area.setFocusable(false);
        jScrollPane7.setViewportView(Txt_Area);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 640, 390));

        Image_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-930x500.jpg"))); // NOI18N
        Image_BG.setPreferredSize(new java.awt.Dimension(930, 530));
        getContentPane().add(Image_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));
        Image_BG.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DisplayTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DisplayTreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DisplayTreeActionPerformed

    private void Btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_InsertActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DisplayActionPerformed

    private void Btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseClicked
        Menu logFrame = new Menu();
        logFrame.pack();
        logFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Btn_BackMouseClicked

    private void Btn_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseEntered
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 51, 51));
    }//GEN-LAST:event_Btn_BackMouseEntered

    private void Btn_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BackMouseExited
        Btn_Back.setFont(new Font("Segoe UI Symbol", Font.BOLD, 60));
        Btn_Back.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Btn_BackMouseExited

    private void Btn_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CreateMouseClicked
        if (exist){
            if (JOptionPane.showConfirmDialog(null, "Create A new empty Tree (This will overwrite the previous tree)", "Create Tree", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
               exist = false;
            }
        }
        
        if (exist == false) {
            try {
                DerivedTree = new TreesAlgo();
                Txt_Area.setText(Txt_Area.getText() + "• Successfully Completed Creating An empty Binary Tree \n\n");
                JOptionPane.showMessageDialog(null, "Successfully Completed Creating An empty Binary Tree", "Create Tree", JOptionPane.INFORMATION_MESSAGE);
                exist = true;
                num_counter = 1;
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Create element - Tree", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_Btn_CreateMouseClicked

    private void Btn_InsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_InsertMouseClicked
       try{
            if (exist){
            String userInput = JOptionPane.showInputDialog(null, "Please enter the element #" + (num_counter), "Insert element - Tree", JOptionPane.INFORMATION_MESSAGE);
            try {
                int int_Input = Integer.parseInt(userInput);
                DerivedTree.insertData(int_Input);
                Txt_Area.setText(Txt_Area.getText() + "• Value " + int_Input + " inserted in the Binary Tree\n\n");
                
              } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "PInsert element - Tree", JOptionPane.INFORMATION_MESSAGE);
              }
            
            } else {
                JOptionPane.showMessageDialog(null, "Please Create first an empty tree", "Insert element - Tree", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Insert element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_InsertMouseClicked

    private void Btn_DisplayTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DisplayTreeMouseClicked
        try {
        if (exist){
            try {
                String levels = DerivedTree.displayParentLeafLevels();
                Txt_Area.setText(Txt_Area.getText() + "• Display of the Tree Structure (Base Traversal):  ");
                Txt_Area.setText(Txt_Area.getText()  + String.valueOf(levels) + " ");
                Txt_Area.setText(Txt_Area.getText()  + "\n");
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
              }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please Create first an empty Tree", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DisplayTreeMouseClicked

    private void Btn_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DisplayMouseClicked
        try {
        if (exist){
            try {
                
                Txt_Area.setText(Txt_Area.getText() + "• Display of the Tree: [  ");
                Txt_Area.setText(Txt_Area.getText()  + String.valueOf(DerivedTree.inorderTraversalData(DerivedTree.root)) + " ");
                Txt_Area.setText(Txt_Area.getText() + "]\n\n");
              } catch (Exception e) {
                // Handle the exception if the user input cannot be converted to an integer
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
              }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please Create first an empty Tree", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Display element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DisplayMouseClicked

    private void Btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DeleteMouseClicked
        try{
            if (exist){
            String userInput = JOptionPane.showInputDialog(null, "Please enter the element #" + (num_counter), "Delete element - Tree", JOptionPane.INFORMATION_MESSAGE);
            try {
                int int_Input = Integer.parseInt(userInput);
                if (DerivedTree.deleteData(int_Input) == 2 ){
                    Txt_Area.setText(Txt_Area.getText() + "• Operation Finished, please click the display to see the results\n\n");
                } 
               
              } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Delete element - Tree", JOptionPane.INFORMATION_MESSAGE);
              }
            
            } else {
                JOptionPane.showMessageDialog(null, "Please Create first an empty Tree", "Delete element - Tree", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.", "Delete element - Tree", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Btn_DeleteMouseClicked


    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_Back;
    private javax.swing.JButton Btn_Create;
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Display;
    private javax.swing.JButton Btn_DisplayTree;
    private javax.swing.JButton Btn_Insert;
    private javax.swing.JLabel Image_BG;
    private javax.swing.JTextArea Txt_Area;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
